---
title: "How to work with git"
author: "AY"
date: "12/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 0: Install git and create a GitHub account 

Of course without installing git on your computer and having a git account you cannot use git. so first do this.

- [installing git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
- [Github account](https://github.com/join)

## Step 1: Create a local git repository 

```shell
$ cd ownCloud/ownCloud_Personal/ownCloud_projects/AG_Cox/github/
$ mkdir myGit
$ cd myGit/
```

To initialize the git repository, one can use the command line as such

```shell
$ git init
```

In my case I will use RStudio, which can create a porject already with versioning control using `git`. It takes an already existing Github repository and uses it, so it doesn't need to be initialized. 

## Step 2: Add a new file to the repo

Here we can add any file we need. Again as I havr already created it via an exiting Github repository, I ahave already a few files in it.

```shell
$ ls
HOWTO_git.Rmd  HOWTO_git.html LICENSE        README.md      myGit.Rproj
```

Using `git status` one can see the status of my git repository and which files in my local folder are known to the repositoy online.

```shell
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        HOWTO_git.Rmd
        HOWTO_git.html
        myGit.Rproj

nothing added to commit but untracked files present (use "git add" to track)
```

A `commit` is a record of what changes you have made since the last time you made a commit. Essentially, you make changes to your repo (for example, adding a file or modifying one) and then tell `git` to put those changes into a `commit`.

How do you tell `git` which files to put into a `commit`? This is where the `staging environment` comes in. As seen above, when you make changes to your repo, `git` notices that a file has changed but won't do anything with it.

To add a file to a `commit`, you first need to add it to the staging environment. To do this, you can use the `git add <filename> command`.

## Step 3: Add a file to the staging environment

This is done using the `git add` command. Again T RStudio takes care of that for you, when one just put the ticks in the Git tab on the left (where is says `Staged` - this is adding to the staging environment).

```shell 
$ git add HOWTO_git.*

$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   HOWTO_git.Rmd
        new file:   HOWTO_git.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        myGit.Rproj
```

Now, after we added the two files, they are ready to be committed. 

## Step 4: Create a commit

By committing the files to the repository they will be added also on the Github website

```shell
$ git commit -m "Adding html files"
[main aca3ae5] Adding html files
 2 files changed, 297 insertions(+)
 create mode 100644 HOWTO_git.Rmd
 create mode 100644 HOWTO_git.html
```

## Step 5: Create a new branch

Ifyou want to make a new feature but are worried about making changes to the main project while developing the feature. This is where git branches come in. 

Branches allow you to move back and forth between 'states' of a project. Official git docs describe branches this way: 

    A branch in Git is simply a lightweight movable pointer to one of these commits.

For instance, if you want to add a new page to your website you can create a new branch just for that page without affecting the main part of the project. Once you're done with the page, you can merge your changes from your branch into the primary branch. When you create a new branch, Git keeps track of which commit your branch 'branched' off of, so it knows the history behind all the files. 

Let's say you are on the primary branch and want to create a new branch to develop your web page. Here's what you'll do: Run `git checkout -b <my branch name>`. This command will automatically create a new branch and then 'check you out' on it, meaning git will move you to that branch, off of the primary branch.

Using this command one can create a new branch and switch to it on-the-fly. 
```shell 
$ git checkout -b my_first_branch
Switched to a new branch 'my_first_branch'
```
```shell
$ git branch
  main
* my_first_branch
```

The `*` symbols shows the active branch.

Switching back to the `main` branch can be done using `switch`

```shell
$ git switch main
M       HOWTO_git.Rmd
M       HOWTO_git.html
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
```










